tasks:
  - before: echo 'Setting up guru shifu. This may take around 5 minutes...'
    init: ./.ignore/init.sh  >> .ignore/log.txt
    command: ./.ignore/start.sh  >> .ignore/log.txt && echo 'Guru Shifu Started'

ports:
  - port: 3000
    onOpen: open-preview
    visibility: public
  - port: 8080
    visibility: public
